name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    container: ghcr.io/cicd-lectures/gitpod:latest
    steps:
      - uses: actions/checkout@v3
      - run: cat README.md | cowsay
