name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
      - run: ls -l
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main
      - run: cat README.md
