name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
      - run: sudo apt update && sudo apt install cowsay
      - uses: actions/checkout@v3
      - run: cat README.md | cowsay
